DROP DATABASE IF EXISTS seq_burgers_db;

CREATE DATABASE seq_burgers_db;

USE seq_burgers_db;

CREATE TABLE Burgers (
id INTEGER(11) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(255) NOT NULL,
devoured BOOLEAN,
createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
updatedAt TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
customerId INTEGER(11),
PRIMARY KEY(id)
);

CREATE TABLE Customers(
id INT AUTO_INCREMENT NOT NULL,
customer_name VARCHAR(255) NOT NULL,
createdAt TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ,
updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
PRIMARY KEY(id)
);